export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const RGISTER_SUCCESS = 'RGISTER_SUCCESS';
export const RGISTER_FAIL = 'RGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const ENABELD_ACCOUNT = 'ENABELD_ACCOUNT';
export const DISABELD_ACCOUNT='DISABELD_ACCOUNT';
export const GET_PROFILE='GET_PROFILE';
export const GET_USERS='GET_USERS';
export const PROFILE_ERROR='PROFILE_ERROR';
export const CLEAR_PROFILE='CLEAR_PROFILE';
export const UPDATE_PROFILE='UPDATE_PROFILE';
export const GET_PROJECT='GET_PROJECT';
export const PROJECT_ERROR='PROJECT_ERROR';
export const GET_EVENT='GET_EVENT';
export const EVENT_ERROR='EVENT_ERROR';
export const GET_EVENT_DETAILS='GET_EVENT_DETAILS';
export const DELETE_EVENT='DELETE_EVENT';
export const GET_DOC='GET_DOC';
export const DOC_ERROR='DOC_ERROR';
export const GET_PROJECT_DETAILS='GET_PROJECT_DETAILS';
export const DELETE_PROJECT='DELETE_PROJECT';
export const GET_GROUP='GET_GROUP';
export const GROUP_ERROR='GROUP_ERROR';
export const GET_GROUP_DETAILS='GET_GROUP_DETAILS';
export const DELETE_GROUP='DELETE_GROUP';
export const ACCOUNT_DELETE='ACCOUNT_DELETE';
export const GET_STUDENTS='GET_STUDENTS';
export const GET_STUDENT='GET_STUDENT';
export const GET_PROFILES='GET_PROFILES';
export const GET_REPOS='GET_REPOS';
export const GET_POST='GET_POST';
export const POST_ERROR='POST_ERROR';
export const GET_POSTS='GET_POSTS';


export const GET_VOTE_PROG='GET_VOTE_PROG';














