export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const RGISTER_SUCCESS = 'RGISTER_SUCCESS';
export const RGISTER_FAIL = 'RGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const ENABELD_ACCOUNT = 'ENABELD_ACCOUNT';
export const DISABELD_ACCOUNT='DISABELD_ACCOUNT';
export const GET_PROFILE='GET_PROFILE';
export const PROFILE_ERROR='PROFILE_ERROR';
export const CLEAR_PROFILE='CLEAR_PROFILE';
export const GET_PROJECT='GET_PROJECT';
export const PROJECT_ERROR='PROJECT_ERROR';








